site_name: Gurklang

nav:
  - Intro: 'index.md'
  - Specification: 'specification.md'
  - Tutorial:
    - 'Basics': 'tutorial/00_basics.md'
    - 'Functions': 'tutorial/01_functions.md'
    - 'Mutable variables': 'tutorial/05_boxes.md'
    - 'Snippets': 'tutorial/99_snippets.md'

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - admonition

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js
  - javascripts/highlighting.js
  - javascripts/definitions.js
  - javascripts/mathJax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - styles/code.css
  - styles/main.css
