site_name: Gurklang

nav:
  - Intro: 'index.md'
  - Specification: 'specification.md'
  - Tutorial:
    - Basics: 'tutorial/00_basics.md'
    - Creating functions: 'tutorial/01_functions.md'
    - 'Mutable variables': 'tutorial/05_boxes.md'

theme:
  name: material
  palette:
    primary: green

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences
  - admonition

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js
  - javascripts/highlighting.js
  - javascripts/definitions.js
extra_css:
  - styles/code.css
