site_name: Gurklang
theme:
  name: material
  palette:
    primary: green

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
